version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: arazzo-mcp-gen #unique name for the tool
    binary: arazzo-mcp-gen #the name of the binary to be generated on the hard drive
    main: . #look in the root dir to get the main.go to start the compilation
    env:
      - CGO_ENABLED=0 #env variables to be set
    ldflags:
      - -X github.com/wso2/arazzo-mcp-gen/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews: #creating the brew formula
  - repository:
      owner: HimethW
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/HimethW/arazzo-mcp-gen
    description: "A CLI tool to generate MCP servers from Arazzo specifications."
    install: |
      bin.install "arazzo-mcp-gen"
    test: |
      system "#{bin}/arazzo-mcp-gen", "--version"

scoops:
  - repository:
      owner: HimethW
      name: scoop-bucket
    homepage: https://github.com/HimethW/arazzo-mcp-gen
    description: "A CLI tool to generate MCP servers from Arazzo specifications."

nfpms:
  - id: arazzo-mcp-gen
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - arazzo-mcp-gen
    vendor: "HimethW"
    maintainer: "HimethW <your-email@example.com>"
    description: "A CLI tool to generate MCP servers from Arazzo specifications."
    homepage: "https://github.com/HimethW/arazzo-mcp-gen"
    formats:
      - deb
      - rpm
      - apk
